# Generated by Django 3.2.2 on 2021-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Read', 'Read'), ('All', 'All')], default='Read', max_length=4),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Manager', 'Manager'), ('Creator', 'Creator')], default='Author', max_length=7),
        ),
    ]
