# Generated by Django 3.2.2 on 2021-05-18 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0005_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Read', 'Read'), ('All', 'All')], default='All', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', through='helpdesk.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
