# Generated by Django 3.2.2 on 2021-05-21 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0010_auto_20210521_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors_tt', through='helpdesk.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
