# Generated by Django 3.2.2 on 2021-05-21 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0011_alter_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', through='helpdesk.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
